
project_id = "urevqqvsadvafgqehzna"

[functions.cleanup-expired-shares]
verify_jwt = false

[functions.send-recovery-email]
verify_jwt = false

[functions.send-share-notification]
verify_jwt = false
