// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urevqqvsadvafgqehzna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyZXZxcXZzYWR2YWZncWVoem5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwODU2NjksImV4cCI6MjA2MzY2MTY2OX0.CootaEB4M5IMW4OQHjB17eACPnMDUFEeUZRO7Ict-TI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);